[build]
  command = "npm run build"
  publish = "www"
  functions = "netlify/functions"

[[edge_functions]]
  path = "/*"
  function = "markdown"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

